$(document).ready(function(){

//BEACH CLEAN-UP MVP

//2 USERS - 1 AT A TIME - FASTEST TIME WINS

//BEACH SET UP
//--> CREATE LITTER LIST
var litter = ['cigarette', 'six-pack', 'balloon' ]
//--> GENERATE RANDOM LITTER
//--> APPEND TO UI

//PLAYER 1
//--> 1. PROMPT PLAYER HOW TO PLAY
//alert("Click the trash to clean up the beach! Fastest wins");
//--> 2. CREATE PLAYER
//--> 3. CREATE VAR SCORE = 0;
//--> 4. CLICK EVENT TO 1) APPENDED TRASH & 2) SETTIMER
//--> 5. ON CLICK REMOVE TRASH AND ADD POINTS TO SCORE
//--> 6. WHEN ALL TRASH IS REMOVED 1) SETTIMEOUT 2) RETURN TOTAL SCORE
//--> 7. STORE PLAYER 1 TIME


//PLAYER 2
//--> SAME AS 1-6
//--> STORE PLAYER 2 TIME

//COMPARE PLAYER 1 to PLAYER 2
//--> Return winner

//BONUS
//1. ASSIGN HIGHER VALUES FOR LARGER LITTER AND
//2. LITTER BEACH WITH SAME TOTAL VALUE FOR EACH USER
//3. TORE SCORES IN COOKIES
//4. RESET SCORES AFTER

});//CLOSES DOCUMENT READY
